### ISSUE TITLE
Docker Swarm and DNS async-dns discovery

### ISSUE THREAD

**Issue by ktoso** [akka/akka-management#261]
Attempting to collect information spread around various channels by @eshepelyuk:

-----
https://gist.github.com/eshepelyuk/5c19350466772af0b7336c95e6614f48
Contents:

TL;DR I've achieved cluster bootstrap working by implementing custom service discovery, 
but interested in how to implement proper approach using Akka's own DNS discovery module.

First, in `Docker Swarm` usage of DNS service discovery is not that straightforward.
Each service (a number of the same containers under the same name) is assigned with `Virtual IP`.
I.e. when resolving service by name - the single `virtual IP` is always returned by `Docker Swarm` internal DNS.
Actual container IPs are hidden behind `virtual IP` and handled by `iptables` (AFAIK) to perform load balancing.

To resolve actual container IPs in overlay network - the name `tasks.${service}` should be used (i.e. `tasks.wallet`, for a service named wallet)
Unfortunately, even using this service naming approach in DNS config, I was not able to achieve cluster self bootstrapping.
According to my observations of the logs, the discovery failed during _probing_ phase.
I.e. actual container IPs were properly resolved, but when trying to reach them - failure happened.

Since I've been trying all this on `Windows` PC - I've tried to run my code on Linux,
the same failure persisted.

Putting some more attention to logs, I've found smth that worried me and could be a failure cause

```
akka_cluster_wallet.2.841e9zk3ztou@default    | 2018-08-08 18:17:21,059 INFO  a.m.c.b.i.BootstrapCoordinator - Located service members with name: [tasks.wallet]: [ResolvedTarget(10.0.0.146,None,Some(/10.0.0.146)), ResolvedTarget(10.0.0.145,None,Some(/10.0.0.145))]
akka_cluster_wallet.2.841e9zk3ztou@default    | 2018-08-08 18:17:21,059 INFO  a.m.c.b.i.BootstrapCoordinator - Ensuring probing actor: contactPointProbe-10.0.0.146-8558
akka_cluster_wallet.2.841e9zk3ztou@default    | 2018-08-08 18:17:21,059 INFO  a.m.c.b.i.BootstrapCoordinator - Ensuring probing actor: contactPointProbe-10.0.0.145-8558

.................................................

akka_cluster_wallet.2.841e9zk3ztou@default    | 2018-08-08 18:17:21,242 DEBUG akka.io.TcpOutgoingConnection - Resolving 10.0.0.145 before connecting
akka_cluster_wallet.2.841e9zk3ztou@default    | 2018-08-08 18:17:21,243 DEBUG akka.io.dns.internal.AsyncDnsManager - Resolution request for 10.0.0.145 from Actor[akka://WalletActorSystem/system/IO-TCP/selectors/$a/48#-2065718425]
akka_cluster_wallet.2.841e9zk3ztou@default    | 2018-08-08 18:17:21,243 WARN  a.io.dns.internal.AsyncDnsResolver - Tried to resolve ip [10.0.0.145]. Ignoring.
```
It's related to [this code](https://github.com/akka/akka/blob/v2.5.14/akka-actor/src/main/scala/akka/io/dns/internal/AsyncDnsResolver.scala#L51).
I've tried to patch Akka version by remove that `case` branch, but had no success.

Then, as soon as I've implemented [extremely stupid custom discovery](https://github.com/eshepelyuk/akka-cluster/blob/master/wallet/src/main/scala/com/newagesol/wallet/SwarmServiceDiscovery.scala) and configured inside `application.conf` - the cluster bootstrapped itself succesfully.
Code of the entire project at [My Github](https://github.com/eshepelyuk/akka-cluster)

Well, so I'd like to get some feedback from Akka developers about the possible reasons, additional details from me, etc., 
to be able to clear this issue up and come up with an ultimate `Akka service discovery` solution for `Docker Swarm` based project.

---

**Comment by ktoso** [comment]
Setting expectations: Docker swarm is not really supported and has not been requested so far.
At the same time, it's something good to look into so thanks for the research. 

I would like to request your patience and refraining from swearing in our community.

**Comment by ktoso** [comment]
This was a bug in the async-dns reimplementation that's relatively fresh. 
Will be resolved by: https://github.com/akka/akka/pull/25452

**Comment by eshepelyuk** [comment]
Compiled SNAPSHOT version and tried, works like a charm. 

Much obliged @ktoso and entire AKKA team !
Feel free to close the issue

**Comment by chbatey** [comment]
Will be fixed in Akka 2.5.15

**Comment by eshepelyuk** [comment]
Fixed naming in the comment above.

**Comment by eshepelyuk** [comment]
@chbatey @ktoso I believe this should be reopened until new version of `akka-discovery-dns` will be released that will be using `Akka 2.5.15`. After upgrade to 2.5.15 I'm receiving this 

```
2018-08-28 16:38:17,555 ERROR akka.actor.ActorSystemImpl - Uncaught error from thread [WalletActorSystem-akka.actor.default-dispatcher-18]: akka.io.dns.DnsProtocol$Resolved.results()Lscala/collection/immutable/Seq;, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[WalletActorSystem]
 java.lang.NoSuchMethodError: akka.io.dns.DnsProtocol$Resolved.results()Lscala/collection/immutable/Seq;
    at akka.discovery.dns.DnsSimpleServiceDiscovery$$anonfun$lookup$2.apply(DnsSimpleServiceDiscovery.scala:59)
    at akka.discovery.dns.DnsSimpleServiceDiscovery$$anonfun$lookup$2.apply(DnsSimpleServiceDiscovery.scala:56)
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
    at scala.util.Try$.apply(Try.scala:192)
    at scala.util.Success.map(Try.scala:237)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.s
```

As far as I see this is caused by API changes in this class `akka.io.dns.DnsProtocol.Resolved`
